/**
 * Generates the United States outline used by the chapter map.
 *
 * Run with: npx tsx scripts/build-us-map.ts
 *
 * The source is us-atlas, which is pre-built TopoJSON from U.S. Census
 * Bureau cartographic boundary files. Projecting here rather than at
 * request time means the browser fetches one cacheable SVG, and the site
 * makes no call to any mapping service: no key, no tiles, no third party
 * learning where CAA's members are.
 *
 * The outline goes to public/ rather than inline, because at roughly 120kb
 * of path data it would otherwise be re-sent with every page render. The
 * projection constants land in lib/us-map.ts so a chapter's latitude and
 * longitude can be placed on the very same outline.
 */
import { writeFileSync } from "node:fs";
import { geoAlbersUsa, geoPath } from "d3-geo";
import { feature, mesh } from "topojson-client";
import topo from "us-atlas/states-10m.json" with { type: "json" };

const WIDTH = 975;
const HEIGHT = 610;
const SCALE = 1300;
const TRANSLATE: [number, number] = [WIDTH / 2, HEIGHT / 2];

const projection = geoAlbersUsa().scale(SCALE).translate(TRANSLATE);
// One decimal place is finer than a pixel at this size and roughly halves
// the payload.
const path = geoPath(projection).digits(1);

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const t = topo as any;
const nation = path(feature(t, t.objects.nation) as never) ?? "";
// Interior borders only, so state lines read as hairlines inside one shape
// rather than as fifty stacked outlines.
const borders = path(mesh(t, t.objects.states, (a, b) => a !== b)) ?? "";

/*
 * Colours are baked in rather than inherited: an SVG referenced through
 * <img> cannot pick up currentColor from the page. These are the CAA
 * tokens, kept in sync with globals.css by hand.
 */
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${HEIGHT}" role="img" aria-label="Map of the United States">
<defs><path id="n" d="${nation}"/></defs>
<use href="#n" fill="#e7ebf1"/>
<path d="${borders}" fill="none" stroke="#ffffff" stroke-width="1" stroke-linejoin="round"/>
<use href="#n" fill="none" stroke="#c3ccda" stroke-width="1.2" stroke-linejoin="round"/>
</svg>
`;

writeFileSync(new URL("../public/map/us-states.svg", import.meta.url), svg);

const ts = `// GENERATED by scripts/build-us-map.ts. Do not edit by hand.
// Source: us-atlas (ISC), built from U.S. Census Bureau boundary files.
//
// These constants describe the projection baked into
// public/map/us-states.svg. Project a point with the same settings and it
// lands where it belongs on that outline.

export const MAP_WIDTH = ${WIDTH};
export const MAP_HEIGHT = ${HEIGHT};
export const MAP_SCALE = ${SCALE};
export const MAP_TRANSLATE: [number, number] = [${TRANSLATE[0]}, ${TRANSLATE[1]}];
export const MAP_SRC = "/map/us-states.svg";
`;

writeFileSync(new URL("../lib/us-map.ts", import.meta.url), ts);
console.log(`wrote public/map/us-states.svg (${(svg.length / 1024).toFixed(0)}kb) and lib/us-map.ts`);
