// GENERATED by scripts/build-us-map.ts. Do not edit by hand.
// Source: us-atlas (ISC), built from U.S. Census Bureau boundary files.
//
// These constants describe the projection baked into
// public/map/us-states.svg. Project a point with the same settings and it
// lands where it belongs on that outline.

export const MAP_WIDTH = 975;
export const MAP_HEIGHT = 610;
export const MAP_SCALE = 1300;
export const MAP_TRANSLATE: [number, number] = [487.5, 305];
export const MAP_SRC = "/map/us-states.svg";
